### ISSUE TITLE
gogetdoc should work even if the package layout is weird

### ISSUE THREAD

**Issue by cflewis** [zmb3/gogetdoc#14]
For reasons I can't get into publicly, I'm working on Go code that doesn't conform to the standard package layout.

The line at https://github.com/zmb3/gogetdoc/blob/master/main.go#L110 causes the whole thing to bail in this case.

I understand that supporting weird package layouts isn't useful, but could there be some workaround so at least if you're trying to get to the standard libraries it still works?

**Comment by jackcohen** [comment]
@cflewis Perhaps there should hooks for a drop-in Go file with your environment specific stuff as is done with goimports in your environment.

**Comment by zmb3** [comment]
I might be able to help you if you shared a little more info about your setup.  Supporting "weird layouts" could mean just about anything.  Can you elaborate?

**Comment by brunnre8** [comment]
I do have the same issue, the error I get is:

    gogetdoc: couldn't get package for /home/$USER/git/go/lca2015/part1/src/main.go: can't find package containing /home/$USER/git/go/lca2015/part1/src/main.go`

@zmb3 any ideas why that happens? I'm obviously doing it the wrong way, but what structure does it expect?

**Comment by dominikh** [comment]
@brunnre8 it expects a valid GOPATH, as outlined in https://golang.org/doc/code.html – and files must be in a package, $GOPATH/src/main.go is not valid, as it's not a package.

**Comment by brunnre8** [comment]
@dominikh thank you for the clarification.

**Comment by cflewis** [comment]
(sorry for taking so long to loop back on this)

Elaboration: Bazel doesn't enforce the same code structure for Go as `go build` does. If I'm not using the `go build` Go structure (e.g. I don't even have a valid GOPATH) gogetdoc breaks. The format/existence of my own package shouldn't be a blocker to my ability to read the standard docs.

**Comment by didrocks** [comment]
I do have somer other setups with symlinks (I'm used to put my projects in separate directory, outside of $GOPATH). `go build` and other go tools are working well with it, apart from gogetdoc.

Here is an example:
~/work/myproject
~/worspace-go/src/myproject -> ~/work/myproject

I can run `go build` and other `gofmt` in ~/work/myproject with success. However running `gogetdoc` says:
`gogetdoc: couldn't get package for foo.go: can't find package containing ~/work/myproject/foo.go`

Do you think support for this would be possible?

**Comment by zmb3** [comment]
Many Go tools generally don't work well with symlinks in your GOPATH.

https://groups.google.com/forum/#!msg/golang-nuts/f5ZYztyHK5I/2Owd4vhdjXEJ
https://github.com/tools/godep/issues/71
https://github.com/joefitzgerald/go-plus/issues/159
https://github.com/golang/go/issues/11305

To answer your question, yes I think supporting this is possible. Whether or not that means we should do it is another story.  It seems to be a rare case, and I'd rather advocate the same message as other tools - don't use symlinks.

**Comment by denispeplin** [comment]
I have same issue. Moved my project to GOPATH to avoid it. Maybe it not that rare for people outside GOLANG community. This is the only language I'm using which forces me to keep my project in a specific place.

**Comment by QantumEntangled** [comment]
I don't know if I'm understanding this correctly, but I BELIEVE this means that to use gogetdoc I have to have my program in the GOPATH/src/ directory? Why is this enforced?

My workflow is currently ~/Code/[language]/[project]/[files] and all my other tools work fine. Is there a way to use gogetdoc on these files without moving my project into ~/.go/src/[project] ? I guess if I'm understanding this correctly I don't see why I would want an unfinished personal project in my GOPATH where I keep libraries.

**Comment by zmb3** [comment]
@QantumEntangled you do need to have your program in `$GOPATH/src`.  I understand that this seems odd to newcomers and those familiar with other languages, but it’s the state of Go right now.  As @denispeplin said - it is the only language [that I’m aware of] that forces you to put your code in a certain place.  I personally hope to see this change, as it puts off a lot of folks.

As for why it’s enforced:  the `go` tool itself requires a GOPATH to build and install Go programs and run tests.  Linters and static analyzers require it to analyze your code.  Tools like `gorename` and `guru` require it in order to operate on your source code.  And lastly, the `go/types` package in the standard library (which `gogetdoc` is built on) requires it to type check your program.

> I don’t see why I would want an unfinished personal project in my GOPATH where I keep libraries.

GOPATH is not a place for only “finished” libraries - it is simply a place where you store your Go code.  GOPATH is just a directory structure - it does not require you to commit or otherwise publish your unfinished source code.
