### ISSUE TITLE
Go get fails on build

### ISSUE THREAD

**Issue by TheDahv** [zmb3/gogetdoc#17]
Current `master` (e2fdf3001b7dbae08213ce1bce7641c54cd47193) fails to build upon `go get` with:

```sh
➜  gogetdoc git:(master) go build
# github.com/zmb3/gogetdoc
./ident.go:142: c.Val().ExactString undefined (type constant.Value has no field or method ExactString)
```

I had to go back to 4a5247b to get to a buildable commit.

**Comment by rabbitear** [comment]
Trying to build this now, got the exact same issue.

**Comment by dominikh** [comment]
You will need Go 1.6 to build gogetdoc.

**Comment by TheDahv** [comment]
Indeed! I just noticed that in the README and it is called out pretty clearly; my fault that I didn't look there before opening the issue.

FWIW, I came to this (and skipped the README) because vim-go uses it as a dependency and I didn't notice the issue until I updated it recently.

**Comment by fatih** [comment]
Yeah, that bite a lot of vim-go users. The `go/types` move has affected most of the tools, so that's why moving forward there is not much we can do.

**Comment by TheDahv** [comment]
It would be nice if the compiler errors could hint at things like that. I can't imagine how an old version of a compiler would be aware of things provided by a future version of a compiler, though.

**Comment by zmb3** [comment]
I'm going to create an issue template to remind people of the Go 1.6 requirement so we don't get so many issues here.

Hopefully as time goes on this becomes less of an issue.  One thing I suggested to the VS Code team (who are hesitant to depend on Go 1.6) is that I could release pre-built binaries for the most common platforms on Github, and editors could just download them directly instead of with `go get`.  Would this be of interest to you, @fatih ?

**Comment by fatih** [comment]
@zmb3 this comes up a lot. I was going to release some binaries in the near future under `github.com/vim-go/` to have control over it. For now the current implementation in vim-go (via go get) is good enough, thanks!
