### ISSUE TITLE
support `builtin` package jump

### ISSUE THREAD

**Issue by leaxoy** [zmb3/gogetdoc#19]
This is a great tool for gophers.
But it can not support jump to source for `builtin` package, for example: `println` can only get doc, but no position.
Could you add this?
Thanks

**Comment by zmb3** [comment]
In short, no.  [Builtins](https://golang.org/src/builtin/builtin.go) are implemented in the compiler and are not standard Go functions. 

You may be interested in this related stack overflow question: https://stackoverflow.com/questions/18512781/built-in-source-code-location

**Comment by mondico** [comment]
The gogetdoc could recognize builtins and display doc extracted from builtin.go as is done in other documentation tools for Go.

**Comment by zmb3** [comment]
@mondico it already does exactly this.

The question was can gogetdoc _also_ provide the location where the builtin is *defined* like it does for normal functions (when using the `-json` format).

**Comment by leaxoy** [comment]
Can we treat it specially for `builtin`, for `builtin`, parse each line to get doc and position. I think do it here is better than do it at downstream(like vscode-go and other tools).

**Comment by zmb3** [comment]
Builtins are not normal Go functions.  Until recently these functions weren't even implemented in Go!  

The problem is not that we can't discover the location - the problem is there isn't a single location.

These functions are generated and not something you would want to take a user to anyway.  You wouldn't want a user looking for documentation to end up in the bowels of the compiler's code.  The godoc should be enough in this case.

Let me know if that makes sense or if you want to discuss further.

https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/mkbuiltin.go
https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/builtin/runtime.go
