### ISSUE TITLE
Add a flag to not fall back on current-package summary

### ISSUE THREAD

**Issue by metaleap** [zmb3/gogetdoc#23]
So `gogetdoc` does its job just *awesomely* well, but this minor quirk bugs me from time to time as slightly irritating: it returns the current-package doc-comment / summary for stuff like operators, keywords, whitespace.. nigh-on anything, seemingly, it couldn't *possibly* find any docs for to begin with. Would be cool if there was either a flag to not do this, or (possibly more straightforward & robust to add) and a new omitempty JSON field that signifies, if set, that the current summary returned was said fallback, so consumers can filter these out should they wish to  =)

**Comment by zmb3** [comment]
Thanks for the kind words, Phil.

I've always meant to go back and fix this, it just hasn't bothered me enough yet.  I'll take a look soon.  I plan to do this without a flag or option - if the cursor isn't over something that has docs I'll just return an error.

**Comment by zmb3** [comment]
After a closer look I recall why I haven't got around to this.

It turns out to be quite difficult.  You see, the package doc you see is not actually a fallback for when we can't find doc - it's the doc we present when we encounter a `*ast.File`. 

There's no (obvious) way to distinguish between when the cursor is on the `package foo` clause or on some other white space out in the file.  In both cases, when you traverse the AST nodes at that position, you end up at a `*ast.File`.  If I remove this case, you'll no longer see package doc for whitespace, but then you won't be able to get doc from a package clause.

**Comment by metaleap** [comment]
Well you'd still see the docs for other packages you hover over, right? I mean when one is working on/in a given package, the need for its summary doc-comment is practically always approx. zero so if no deeper traversal from top-level ast.File occurs, could still in theory ditch the package doc.. I mean, not a pressing neeed, but a mouse-heavy user kinda gets a little confused in the heat of the moment as he jumps around linter/error-squiggly-underlined portions of code to always keep bumping into that same old lame old current-package doc --- I'm **in** the package so chances are, I have a rough idea what it's for  🤣

**Comment by zmb3** [comment]
You convinced me.  Let's give it a try and see if we get complaints.
