### ISSUE TITLE
Add build tag support

### ISSUE THREAD

**Issue by ramya-rao-a** [zmb3/gogetdoc#25]
See https://github.com/Microsoft/vscode-go/issues/1024

`gogetdoc` fails to give definition info when there is a build tag in the file

**Comment by zmb3** [comment]
I'll go ahead and add a `-tags` flag that will behave the same way as `gorename`'s flag.

The editor needs to figure out which flags to pass, which may be tricky.  If you have project-specific settings this is probably a good place for a configuration setting.

Automatically determining which build tags to pass would be nice, but you can probably only do that in certain cases.  For example, in the linked issue for vscode-go, you can probably make the assumption that since the file passed to `gogetdoc` is `package main` and has build tags on it, you should specify those build tags by default.
