### ISSUE TITLE
full package documentation

### ISSUE THREAD

**Issue by apiarian** [zmb3/gogetdoc#29]
Would it be possible to return full package documentation like the output of `godoc` with the full docs for the package *and* all of the exported things.

In contrast to the current behavior of only showing the `package` level docs when pointing at a package. Also in contrast to the `go doc` behavior of showing just the `package` level docs and a *list* of the other exported things.

I've actually been able to chain `gogetdoc` to find the package location (to correctly handle things like vendor overrides and packages that only appear in the vendor directory), and godoc. But that was done manually. I'm sure I could script it, but it may be generally handy to get the full package docs.

Asking in conjunction with https://github.com/Microsoft/vscode-go/issues/1237

**Comment by zmb3** [comment]
Hi @apiarian!

I'm not sure this fits within the scope of `gogetdoc`.  This tool is intended to provide focused documentation (like a tooltip) based on a very specific piece of code.  It is not meant as a replacement for anything and everything related to docs.  

As you mention, `godoc` and `go doc` cover most of these use cases already.  Perhaps the limitations you're seeing with the vendor directory should be reported to the Go team and fixed in those tools.  I'm not sure it's worth the trouble to maintain an extra copy of functionality that already exists elsewhere.

What do you think?  Does this seem reasonable?

**Comment by apiarian** [comment]
Sounds quite sensible indeed. I'll see if I can get this raised with `godoc` since that seems to be the most promising output of what I'm looking for. It just doesn't really respect the local `vendor/` directory`.
