### ISSUE TITLE
Can't build under go1.6

### ISSUE THREAD

**Issue by ericychoi** [zmb3/gogetdoc#3]
Even under go1.6, I can't get it to build

```
% go build
# github.com/zmb3/gogetdoc
./ident.go:18: impossible type assertion:
	*"go/types".PkgName does not implement "golang.org/x/tools/go/types".Object (wrong type for Parent method)
		have Parent() *"go/types".Scope
		want Parent() *"golang.org/x/tools/go/types".Scope
% go version
go version go1.6 darwin/amd64
```

Any ideas?

**Comment by zmb3** [comment]
It sounds like you have an older version of `golang.org/x/tools` that still depends on the `go/types` package there.  In the last couple months the tools repo was updated to import `go/types` from the standard library.

Try doing a `go get -u` to update dependencies, or even just setting up a separate GOPATH so that we can be sure you're getting the latest version of everything.

**Comment by ericychoi** [comment]
thanks! problem solved

**Comment by thurt** [comment]
thank you!
